import { Geist, Geist_Mono } from 'next/font/google';
import React from 'react';

import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import SocketProvider from '@/context/socket-context';
import QueryClientProvider from '@/providers/query-client-provider';

import type { Metadata } from 'next';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryClientProvider>
          <SocketProvider>
            {children}
            <Toaster />
          </SocketProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
